apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-alertmanager
  labels:
    alertmanagerConfig: socks-shop
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 15m
    receiver: "slack"
  receivers:
  - name: 'slack'
    slackConfigs:
      - channel: "#test-alerting"
        apiURL:
          name: slack-config
          key: apiSecret
  # - name: 'opsgenie'
    opsgenieConfigs:
      -  apiKey: 
           name: opsgenie-config
           key: apiSecret
         responders:
         - name: 'Alerts'
           type: 'teams'

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-config
data:
  apiSecret: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxSkZLNUFCOEMvQjA1MVdERjhNMzgvbmFGakt5UGdTcFF2QkRPOENGb3ROUDQ2      
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: opsgenie-config
data:
  apiSecret: YmIxZTMwYzUtMzZmZC00MzA0LWI3ZmYtYjgwMWU0YmY5NzVk
      
